name: Action_Build_android_markw_kernel_xiaomi_marke_new

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-22.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main

      - name: Get variable configuration...
        run: |
          echo "BUILD_TIME=$(date +%s | md5sum | awk '{print substr($1,1,10)}')" >> $GITHUB_ENV

      - name: Configuration Environment
        run: |
          sudo apt update && sudo apt -y dist-upgrade
          sudo apt install -y gcc g++ python make texinfo texlive bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip language-pack-zh-hans
          git config --global user.name "Mochen"
          git config --global user.email "mochen20070702@gmail.com"

      - name: Clone device kernel
        run: |
          cd $GITHUB_WORKSPACE
          git clone --depth=1 https://github.com/Allenwdk/android_kernel_xiaomi_markw_new.git -b T

      - name: Download gcc && Building kernel
        run: |
          cd $GITHUB_WORKSPACE/android_kernel_xiaomi_markw_new
          BuildTime=$(date +%Y_%m_%d)
          echo -e "--------------------开始下载 GCC--------------------\n"
          aria2c "https://developer.arm.com/-/media/Files/downloads/gnu-a/10.3-2021.07/binrel/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz?rev=1cb9c51b94f54940bdcccd791451cec3&hash=A56CA491FA630C98F7162BC1A302F869"
          xz -d gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar.xz
          tar xf gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar
          rm gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu.tar
          echo -e "--------------------开始Build--------------------\n"
          export ARCH=arm64
          export SUBARCH=arm64
          export CROSS_COMPILE=${PWD}/gcc-arm-10.3-2021.07-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-
          make clean
          make mrproper
          make O=out markw_defconfig
          make -j$(nproc) O=out 2>&1 | tee $BuildTime-BuildKernel.log
          
      - name: Upload to WeTransfer
        run: |
              cd $GITHUB_WORKSPACE/android_kernel_xiaomi_markw_new/
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet ./out/arch/arm64/boot/Image.gz-dtb
