name: Build_Kernel

on:
  workflow_dispatch:

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04
    
    steps:
      - name: Get the source code of this repositorie...
        uses: actions/checkout@main

      - name: Configuration Environment
        run: |
          sudo apt update && sudo apt -y dist-upgrade
          sudo apt install -y gcc g++ python make texinfo texlive bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip language-pack-zh-hans
          git config --global user.name "Mochen"
          git config --global user.email "mochen20070702@gmail.com"

      - name: Download gcc
        run: |
          cd $GITHUB_WORKSPACE
          aria2c "https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz"
          xz -d gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar.xz
          tar xf gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu.tar

      - name: Clone kernel trees && Build kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH=~/gcc-arm-9.2-2019.12-x86_64-aarch64-none-linux-gnu/bin:$PATH
          export CROSS_COMPILE=aarch64-none-linux-gnu-
          git clone https://github.com/harvasyuk/android_kernel_xiaomi_msm8953.git -b Q-Non-treble
          cd android_kernel_xiaomi_msm8953
          make clean
          make mrproper
          args="-j$(nproc --all) O=out ARCH=arm64 SUBARCH=arm64 CROSS_COMPILE=aarch64-none-linux-gnu-"
          make ${args} O=markw_defconfig
          make -j$(nproc)


